#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the solve function below.


if __name__ == '__main__':
    meal_cost = float(input().strip())
 
    tip_percent = int(input().strip())

    tax_percent = int(input().strip())
    tip = meal_cost * tip_percent / 100
    tax = meal_cost * tax_percent / 100
    totalcost = meal_cost + tip + tax 
    print(str(round(totalcost)))
